name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build and deploy
        run: |
          npm run build
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mv out ./docs
          git add docs
          git commit -m "Deploy to GitHub Pages"
          git push origin -f main:gh-pages